beelab_paypal:
    username: "talentmaajabu466_api1.gmail.com"
    password: "PUKZUZR26ZNN3FXP"
    signature: "An4jKYyOSvK91UCDJqRegMA7vKcsAPo-DzRbBokD9-fx1PTjKFlhviIK"
    return_route: "app_payment_complete"
    cancel_route: "app_payment_canceled"
    test_mode: false
    currency: "USD"