# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }

    admin.video:
        class: App\Admin\VideoAdmin
        arguments: [~, App\Entity\Video, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Video }

    admin.plan:
        class: App\Admin\PlanAdmin
        arguments: [~, App\Entity\Plan, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Plan }

    admin.candidate:
        class: App\Admin\CandidateAdmin
        arguments: [~, App\Entity\Candidate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Candidate }

    admin.votemode:
        class: App\Admin\VoteModeAdmin
        arguments: [~, App\Entity\VoteMode, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: VoteMode }
    admin.vote:
        class: App\Admin\VoteAdmin
        arguments: [~, App\Entity\Vote, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Votes }

    admin.candidates_has_media:
        class: App\Admin\CandidateHasMediaAdmin
        arguments: [~, App\Entity\CandidateHasMedia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CandidateHasMedias }
